package to.eyed.inferno.ui

// Every user-facing string lives here (hard-coded English, no strings.xml except app_name for
// the manifest). Grouped by screen; other packages add members, never rename.
object S {
    const val appName = "Inferno"

    // Generic actions
    const val ok = "OK"
    const val cancel = "Cancel"
    const val close = "Close"
    const val back = "Back"
    const val dismiss = "DISMISS"
    const val confirm = "Confirm"
    const val delete = "Delete"
    const val retry = "Retry"
    const val resume = "Resume"
    const val apply = "Apply"
    const val save = "Save"
    const val copy = "Copy"
    const val copied = "Copied"
    const val manage = "Manage"
    const val download = "Download"
    const val recommended = "Recommended"
    const val default = "Default"
    const val more = "More"
    const val tapAgainToConfirm = "Tap again to confirm. Irreversible."

    // Chat
    const val newChat = "New chat"
    const val openSidebar = "Open sidebar"
    const val closeSidebar = "Close sidebar"
    const val chooseModel = "Choose a model"
    const val chooseModelToStart = "Choose a model to start"
    const val chooseModelButton = "Choose model"
    const val emptyTitle = "Where should we begin?"
    const val emptySubtitle = "Runs entirely on this phone."
    const val composerPlaceholder = "Message Inferno…"
    const val composerLoadModelToStart = "Load a model to start"
    const val send = "Send"
    const val stop = "Stop"
    const val attach = "Attach"
    const val camera = "Camera"
    const val photos = "Photos"
    const val think = "Think"
    const val thinking = "Thinking…"
    const val thoughtFor = "Thought for"
    const val jumpToLatest = "Jump to latest"
    const val regenerate = "Regenerate"
    const val details = "Details"
    const val edit = "Edit"
    const val attachedImage = "Attached image"
    const val fullSizeImage = "Full-size image"
    const val removeImage = "Remove image"
    const val willSendWhenReady = "Will send when the model is ready"
    const val trimmingOlder = "Trimming older messages…"
    const val olderOutsideContext = "Older messages are outside the context window"
    const val contextAlmostFull = "Context is almost full"
    const val trimOlderMessages = "Trim older messages"
    const val answerComplete = "Answer complete"
    const val stopped = "stopped"
    const val interrupted = "interrupted"
    const val finishCurrentAnswer = "Finish the current answer first"
    const val couldNotReadImage = "Couldn't read that image"
    const val notEnoughMemoryForImage = "Not enough memory to read this image"
    const val messageExceedsContext = "This message alone exceeds the model's memory. Shorten it or start a new chat."
    const val phoneIsHot = "Phone is hot — running on fewer cores"
    const val noVision = "This model has no vision"
    const val noMemoryForVision = "Not enough memory for images with this model"
    const val turnDetails = "Turn details"
    const val messageActions = "Message actions"
    const val copyAsJson = "Copy as JSON"

    // Sidebar
    const val search = "Search"
    const val searchChats = "Search chats"
    const val noChatsYet = "No chats yet"
    fun noChatsMatch(query: String) = "No chats match \"$query\""
    const val pinned = "Pinned"
    const val today = "Today"
    const val yesterday = "Yesterday"
    const val previous7Days = "Previous 7 days"
    const val older = "Older"
    const val archived = "Archived"
    const val rename = "Rename"
    const val pin = "Pin"
    const val unpin = "Unpin"
    const val archive = "Archive"
    const val unarchive = "Unarchive"
    const val models = "Models"
    const val noModelLoaded = "No model loaded"
    const val benchmark = "Benchmark"
    const val settings = "Settings"

    // Engine states
    const val loading = "Loading…"
    const val calibrating = "Calibrating…"
    const val readingWeights = "Reading weights"
    const val creatingContext = "Creating context"
    const val loadingVision = "Loading vision"
    const val failed = "Failed"
    const val suspended = "Suspended"
    fun loadingModel(name: String) = "Loading $name…"

    // Models
    const val model = "Model"
    const val getModels = "Get models"
    const val nothingDownloadedYet = "Nothing downloaded yet"
    const val curatedForThisPhone = "Curated for this phone"
    const val contextLength = "Context length"
    const val generation = "Generation"
    const val importGguf = "Import GGUF"
    const val discardDownload = "Discard download"
    const val paused = "paused"
    const val noConnection = "no connection"
    const val pausedBySystem = "paused by the system"
    const val waitForWifi = "Wait for Wi-Fi"
    const val downloadAnyway = "Download anyway"
    const val alwaysAllow = "Always allow"
    const val offlineNotice = "You're offline. Downloaded models still work."
    const val notificationsNotice = "Enable notifications to see download progress in the shade"
    const val q4Footer = "Q4_0 files run fastest on this phone (KleidiAI dotprod kernels). Q8_0 mmproj recommended."
    const val autoMax = "Auto (max)"
    const val contextNote = "Auto picks the largest context that fits in memory. Q8_0 halves KV memory and requires flash attention."

    // Settings
    const val inference = "Inference"
    const val chat = "Chat"
    const val storage = "Storage"
    const val advanced = "Advanced"
    const val about = "About"
    const val dangerZone = "Danger zone"
    const val systemPrompt = "System prompt"
    const val streamingAnimations = "Streaming animations"
    const val haptics = "Haptics"
    const val appliedAfterReload = "Applied after reload"
    const val openSourceLicences = "Open-source licences"
    const val sourceCode = "Source code"
    const val privacy = "Privacy"
    const val privacyLine = "Nothing leaves this phone."
    const val deleteAllChats = "Delete all chats"
    const val deleteAllModels = "Delete all models"
    const val chatsStoredLocally = "Chats are stored only on this device."

    // Onboarding
    const val firstRunTagline = "Private AI that runs on your phone. Nothing leaves the device."
    const val downloadAndStart = "Download and start"
    const val chooseDifferentModel = "Choose a different model"
    const val importAGguf = "Import a GGUF"
    const val unsupportedCpu = "This phone's CPU lacks the dotprod/fp16 instructions Inferno needs."

    // Bench
    const val loadModelFirst = "Load a model first"
    const val runQuick = "Run quick (pp512 / tg128)"
    const val runThreadMatrix = "Run thread matrix"
    const val runBenchmarkHint = "Run a benchmark to see numbers for this phone"
    const val shareJson = "Share JSON"

    // Accessibility labels for decorative / structural elements
    const val dragHandle = "Drag handle"
    const val selected = "Selected"

    // Chat UI (WP7 additions)
    const val createImage = "Create image"
    const val gallery = "Gallery"
    const val generatingImage = "Generating image…"
    const val stopCurrentAnswer = "Stop the current answer first"
    const val readingImage = "Reading image"
    fun readingTokens(n: Int) = "Reading ${String.format(java.util.Locale.US, "%,d", n)} tokens…"
    const val preparing = "Preparing…"
    const val copyMessage = "Copy message"
    const val copyCode = "Copy code"
    const val messageCopied = "Copied"
    const val editMessage = "Edit message"
    const val resend = "Resend"
    const val openImage = "Open image"
    const val closeImage = "Close image"
    const val contextRing = "Context"
    fun contextUsed(percent: Int) = "Context $percent% used"
    fun contextAlmostFullBody(used: String, total: String) = "$used of $total tokens used. Start a new chat or trim older messages."
    const val reasoning = "Reasoning"
    fun thoughtFor(duration: String) = "Thought for $duration"
    const val suggestionExplain = "Explain something simply"
    const val suggestionDraft = "Draft a message"
    const val suggestionPhoto = "Describe a photo"
    const val suggestionIdeas = "Brainstorm ideas"
    const val promptExplain = "Explain how neural networks learn, in plain words."
    const val promptDraft = "Draft a short, warm message to a friend I haven't seen in a while."
    const val promptIdeas = "Give me five ideas for a weekend project."
    const val newChatTitle = "New chat"
    const val chatTitle = "Chat title"
    const val renameChat = "Rename chat"
    const val deleteChat = "Delete chat"
    const val tapAgainToDelete = "Tap again to delete"
    const val modelRow = "Model"
    const val promptTokens = "Prompt tokens"
    const val reusedFromCache = "reused"
    const val generatedTokens = "Generated tokens"
    const val prefill = "Prefill"
    const val decode = "Decode"
    const val imageEncode = "Image encode"
    const val contextUsedRow = "Context used"
    const val finishReason = "Finish reason"
    const val sampling = "Sampling"
    const val template = "Template"
    const val chatmlFallback = "chatml fallback"
    const val thinkingTime = "Thinking"
    const val jumpToLatestDescription = "Scroll to the latest message"
    const val attachMenu = "Attach photo"
    const val thinkOn = "Thinking on"
    const val thinkOff = "Thinking off"

    // ---- WP8: models / settings / onboarding / bench ----
    const val load = "Load"
    const val loaded = "Loaded"
    const val notDownloaded = "Not downloaded"
    const val queued = "Queued"
    const val verifying = "Verifying…"
    const val downloaded = "Downloaded"
    const val vision = "vision"
    const val textOnly = "text only"
    const val imported = "Imported"
    const val importedLicence = "Unknown licence (imported)"
    const val lfmLicenceNote = "LFM Open License v1.0 (non-commercial limits apply)"
    const val manageModels = "Manage models"
    const val downloadedModels = "Downloaded"
    const val importedModels = "Imported"
    const val imageModels = "Image models"
    const val usedForCreate = "Used on the Create screen"
    const val storageFooter = "Files live in this app's private storage and are removed with the app."
    const val deleteModel = "Delete model"
    const val discardPartial = "Discard partial download"
    const val downloadConfirmTitle = "Download"
    const val importTextModel = "Choose the model file (.gguf)"
    const val importProjector = "Add a vision projector (mmproj)"
    const val importSkipProjector = "Skip"
    const val importName = "Display name"
    const val importNamePlaceholder = "From the file header"
    const val importTitle = "Import GGUF"
    const val importCardHint = "A .gguf from your files"
    const val importHint = "Q4_0 text models run fastest here. A projector is optional and enables images."
    const val importing = "Importing…"
    const val pairWith = "Attach to"
    const val loadModel = "Load a model to change its context."
    const val tokens = "tokens"
    const val autoContextDescription = "Largest context that fits in memory right now."
    const val kvCache = "KV cache"
    const val estimatedTotal = "estimated total"
    const val memoryBudget = "of the memory budget"
    const val weights = "weights"
    const val kv = "KV"
    const val compute = "compute"
    const val visionMem = "vision"
    const val noModelSelected = "No model selected"
    const val needsFree = "Needs"
    const val available = "available"
    fun needsMemory(need: String, avail: String) = "Needs ~$need GB of memory, $avail GB usable right now"
    fun downloadOf(done: String, total: String) = "$done of $total"
    fun perSecond(rate: String) = "$rate/s"

    // Settings
    const val performance = "Performance"
    const val custom = "Custom"
    const val preset = "Preset"
    const val presetAuto = "Auto"
    const val presetMax = "Max"
    const val presetCool = "Cool"
    const val presetDescription = "Auto balances speed and heat. Max holds the clocks up. Cool keeps a core free."
    const val imageDetail = "Image detail"
    const val keepModelLoaded = "Keep model loaded"
    const val keepModelLoadedDesc = "Stay ready in the background. Uses memory while idle."
    const val computeRow = "Compute"
    const val useModelDefaults = "Use the model's sampling"
    const val useModelDefaultsDesc = "Recommended values from the model card."
    const val temperature = "Temperature"
    const val topP = "Top-p"
    const val topK = "Top-k"
    const val minP = "Min-p"
    const val repeatPenalty = "Repeat penalty"
    const val presencePenalty = "Presence penalty"
    const val maxTokens = "Max tokens"
    const val maxTokensDesc = "0 = until the answer ends"
    const val resetToDefaults = "Reset"
    const val thinkingToggle = "Thinking"
    const val thinkingDesc = "Reason before answering. Slower, better on hard questions."
    const val thinkingUnavailable = "The loaded model has no thinking mode."
    // Context policy (Settings > Chat) and the chat surfaces it drives
    const val contextPolicy = "When the context fills up"
    const val policyRolling = "Rolling"
    const val policyCompact = "Compact"
    const val policyStop = "Stop"
    const val policyRollingDesc = "Oldest messages are dropped from the model's memory; the chat history stays."
    const val policyCompactDesc = "Older messages are summarized by the model so the conversation can continue."
    const val policyStopDesc = "Sending pauses when the context is full; start a new chat."
    const val compacting = "Compacting…"
    const val compactingDesc = "Summarizing older messages"
    const val compactNow = "Compact now"
    const val summaryOfEarlier = "Summary of earlier messages"
    const val carriedOverSummary = "Carried over from an earlier chat"
    fun compactedMessages(n: Int) = "Compacted $n messages"
    const val contextFullTitle = "This chat has reached the model's memory limit"
    fun contextFullBody(used: String, total: String) = "$used of $total tokens used. Nothing is dropped under the Stop policy."
    const val carryOverSummary = "Carry over a summary"
    const val switchToRolling = "Switch to rolling"
    const val streamingAnimationsDesc = "Caret, dots and the breathing mark."
    const val hapticsDesc = "Ticks on send, ready and errors."
    const val modelsStorage = "Models"
    const val allowMetered = "Allow downloads over mobile data"
    const val allowMeteredDesc = "Otherwise each download asks first."
    const val clearImageCache = "Clear image cache"
    const val clearImageCacheDesc = "Camera captures waiting to be sent."
    const val clear = "Clear"
    const val threads = "Threads"
    fun bigCoresDetected(n: Int) = "$n big cores detected. More threads is slower on this phone."
    const val pinBigCores = "Pin to big cores"
    const val pinBigCoresDesc = "Keep the workers off the efficiency cores."
    const val flashAttention = "Flash attention"
    const val flashAttentionDesc = "Fused attention; faster with long contexts."
    const val requiredForQuantizedKv = "Required for quantized KV"
    const val kvCacheDesc = "Q8_0 halves KV memory; Auto picks it for large caches."
    const val mmap = "Memory-map weights"
    const val mmapDesc = "Off uses direct reads; try if loading is slow."
    const val poll = "Poll"
    const val pollDesc = "How eagerly idle workers spin. Higher is faster and warmer."
    const val logLevel = "Native log level"
    const val runBenchmark = "Run benchmark"
    const val runBenchmarkDesc = "pp512 / tg128 on this phone"
    const val systemInfo = "System info"
    const val systemInfoDesc = "ggml build features"
    const val privacyDesc = "No accounts, no analytics, no network beyond model downloads."
    const val licencesDesc = "llama.cpp, stable-diffusion.cpp, KleidiAI and friends"
    const val sourceDesc = "github.com/cesp99/Inferno"
    const val sourceUrl = "https://github.com/cesp99/Inferno"
    const val deleteAllChatsDesc = "Chats are stored only on this device."
    const val deleteAllModelsDesc = "Frees the storage. The current model is closed first."
    const val systemPromptDesc = "Applies to new turns; changes the cached prefix."
    const val systemPromptPlaceholder = "You are a helpful assistant…"
    const val noSystemPrompt = "None"
    const val fast = "Fast"
    const val balanced = "Balanced"
    const val highDetail = "High"
    fun imageDetailDesc(tokens: Int, seconds: String?) = if (seconds != null) "≈ $tokens image tokens, about $seconds per image" else "≈ $tokens image tokens per image"
    fun measuredLine(tps: String, threads: Int, pinned: Boolean) = "$tps $tokPerSec with $threads ${if (pinned) pinnedCores else freeCores} cores"
    fun estimatedLine(est: String) = "~$est $tokPerSec estimated"
    fun modelsStorageLine(n: Int, bytes: String, partial: String?) = "$n on disk · $bytes${partial?.let { " · $it partial" } ?: ""}"

    // Onboarding
    const val promise = "Private. Offline. Yours."
    const val freeSpaceWarning = "Low storage: keep at least twice the model size free."
    const val autoLoadsWhenDone = "Loads by itself when the download finishes."
    const val startingUp = "Getting ready…"
    const val detectedFeatures = "Detected"
    const val unsupportedBody = "Inferno's engine is compiled for Armv8.2 with dotprod and fp16. This CPU does not report them, so the app cannot run here."

    // Bench
    const val benchIdle = "Run a benchmark to see numbers for this phone"
    const val prompt = "prompt"
    const val benchGenerate = "generate"
    /** Word joiners keep "tok/s" on one line at large font scales. */
    const val tokPerSec = "tok\u2060/\u2060s"
    const val thermalLabel = "Thermal"
    const val headroom = "headroom"
    const val running = "Running…"
    const val quickRunDesc = "Three passes of pp512 / tg128 on the current settings."
    const val matrixDesc = "Thread and KV variants, about two minutes. Keeps the phone busy."
    const val label = "Run"
    const val thr = "thr"
    const val chooseModelForBench = "Benchmarks run on the loaded model."
    val thermalNames = listOf("nominal", "light", "moderate", "severe", "critical", "emergency", "shutdown")

    // Create image / Gallery (WP9b-ui)
    const val create = "Create"
    const val describeImage = "Describe the image…"
    const val generate = "Generate"
    const val imageModel = "Model"
    const val options = "Options"
    const val size = "Size"
    const val steps = "Steps"
    const val seed = "Seed"
    const val randomSeed = "Random"
    const val randomSeedHint = "New every time"
    const val useRandomSeed = "Use a random seed"
    const val reuseLastSeed = "Reuse last seed"
    const val copySeed = "Copy seed"
    const val fewerSteps = "Fewer steps"
    const val moreSteps = "More steps"
    const val saveToPhotos = "Save"
    const val savedToPhotos = "Saved to Photos"
    const val share = "Share"
    const val useAsAttachment = "Attach"
    const val again = "Again"
    const val waiting = "Waiting…"
    const val discard = "Discard"
    const val downloading = "Downloading"
    const val resumeDownload = "Resume download"
    const val retryDownload = "Retry download"
    const val noImagesYet = "No images yet"
    const val noImagesHint = "Images you create will appear here."
    const val generatedImage = "Generated image"
    const val latentPreview = "Preview"
    const val deleteImage = "Delete image"
    const val starting = "Starting"
    const val finishing = "Finishing"
    const val describeFirst = "Describe the image first"
    fun loadingImageModel(name: String) = "Loading $name…"
    fun stepOf(step: Int, total: Int) = "Step $step/$total"
    fun downloadModel(name: String, size: String) = "Download $name · $size"
    fun square(px: Int) = "$px × $px"

    /** "~12 s" / "~1 min" / "~1 min 8 s": whole seconds, minutes once past 60. */
    fun eta(seconds: Int): String {
        val s = seconds.coerceAtLeast(0)
        if (s < 60) return "~$s s"
        val m = s / 60
        val r = s % 60
        return if (r == 0) "~$m min" else "~$m min $r s"
    }

    /** "8.1 s" / "1 min 8 s" (6.2): one decimal under a minute, whole seconds above. */
    fun duration(ms: Long): String {
        val s = ms / 1000.0
        if (s < 60) return String.format(java.util.Locale.US, "%.1f s", s)
        val m = (s / 60).toInt()
        val r = (s - m * 60).toInt()
        return if (r == 0) "$m min" else "$m min $r s"
    }

    // ---- Experience level (Settings > Experience; data/DevFlags.kt readers) ----
    const val experience = "Experience"
    const val levelNormal = "Normal"
    const val levelPower = "Power user"
    const val levelDeveloper = "Developer"
    const val levelNormalDesc = "Just chat. Sensible defaults, nothing technical."
    const val levelPowerDesc = "Control context, prompts and generation."
    const val levelDeveloperDesc = "Everything, including engine internals and timings."
    const val context = "Context"
    const val photoQuality = "Photo quality"
    const val photoQualityDesc = "How closely the model looks at attached photos. Higher is slower."
    const val stayReady = "Stay ready in the background"
    const val stayReadyDesc = "Answers start straight away when you come back. Uses memory while idle."
    const val mayBeTooLarge = "May be too large for this phone"
    const val olderForgotten = "The model no longer remembers the messages above"
    const val readingMessages = "Reading the conversation…"
    const val contextReducedPlain = "Using a shorter memory for this chat so the model fits in this phone."
    const val contextNotePlain = "Auto picks the largest context that fits in memory."
    fun version(v: String) = "Inferno $v"

    // ---- Developer mode (ui/settings/DeveloperPage.kt) ----
    const val developer = "Developer"
    const val developerRowDesc = "Diagnostics toggles, log level and engine facts."
    const val on = "On"
    const val off = "Off"
    const val devShowSection = "Show"
    const val devGenerationStats = "Generation stats"
    const val devGenerationStatsDesc = "tok/s, token counts and timings under the latest answer."
    const val devContextMeter = "Context meter"
    const val devContextMeterDesc = "The usage ring in the model chip."
    const val devTurnDetails = "Turn details"
    const val devTurnDetailsDesc = "The Details action on every answer."
    const val devBenchmark = "Benchmark"
    const val devBenchmarkDesc = "The Benchmark screen in the sidebar and under Advanced."
    const val devModelTechSpecs = "Model tech specs"
    const val devModelTechSpecsDesc = "Quantisation, context, tok/s and KV size on model rows."
    const val devThermalInfo = "Compute and thermal"
    const val devThermalInfoDesc = "Threads, cores and thermal status in the chat and in Settings."
    const val devTokenCounter = "Live token counter"
    const val devTokenCounterDesc = "Token count and speed while an answer streams."
    const val engineLogSection = "Engine log"
    const val engineLogLevel = "Log level"
    const val engineLogLevelDesc = "Floor for llama.cpp messages in logcat (tag inferno-native)."
    const val logVerbose = "Verbose"
    const val logInfo = "Info"
    const val logWarn = "Warn"
    const val engineSection = "Engine"
    const val llamaCppRow = "llama.cpp"
    const val sdCppRow = "stable-diffusion.cpp"
    const val cpuRow = "CPU"
    const val cpuFeaturesRow = "CPU features"
    const val threadsRow = "Threads"
    const val thermalRow = "Thermal"
    const val sustainedRow = "Sustained mode"
    const val modelBuffersRow = "Model buffers"
    const val loadTimeRow = "Load time"
    const val calibrationRow = "Calibration"
    const val contextRow = "Context"
    const val notAvailable = "—"
    const val requested = "requested"
    const val fullSystemInfo = "Full system info"
    const val tierFast = "Fast"
    const val tierBalanced = "Balanced"
    const val tierQuality = "Best quality"
    const val importedBlurb = "Imported from your files."
    fun aboutPerImage(seconds: String) = "About $seconds per image"
    fun liveTokens(n: Int, tps: String) = "${String.format(java.util.Locale.US, "%,d", n)} tokens · $tps $tokPerSec"

    // ViewModel notices (AppViewModel / ChatViewModel / ImageGenViewModel / BenchViewModel): fallbacks after `e.message ?:`
    fun crashedWhileLoading(name: String) = "Inferno crashed while loading $name. Tap the model chip to try again or choose a smaller context."
    fun notDownloaded(name: String) = "$name is not downloaded"
    fun contextReducedTo(tokens: String) = "Context reduced to $tokens tokens to fit in memory"
    const val couldNotLoadModel = "Could not load the model"
    const val couldNotUnload = "Could not unload"
    const val couldNotApplySetting = "Could not apply the setting"
    const val couldNotChangeThreads = "Could not change threads"
    const val imageCacheCleared = "Image cache cleared"
    const val couldNotDelete = "Could not delete"
    fun importedModel(name: String) = "Imported $name"
    const val importFailed = "Import failed"
    const val systemInfoUnavailable = "unavailable"
    const val waitForImageFirst = "Wait for the image to finish first"
    const val chooseModelFirst = "Choose a model first"
    const val generationFailed = "Generation failed"
    const val compactionFailed = "Compaction failed"
    const val nothingToCompact = "Nothing to compact yet"
    const val nothingToCarryOver = "Nothing to carry over"
    const val chatFallbackTitle = "Chat"
    fun continuedTitle(title: String) = "Continued · $title"
    fun oldestMessagesDropped(n: Int) = "$n oldest messages did not fit the summary"
    const val downloadImageModelFirst = "Download the image model first"
    const val couldNotSaveToPhotos = "Couldn't save to Photos"
    const val couldNotShareImage = "Couldn't share the image"
    const val waitForModelReady = "Wait for the model to be ready"
    const val benchmarkFailed = "Benchmark failed"
    fun benchVariantSkipped(kv: String, reason: String?) = "16k $kv skipped: $reason"
    const val benchQuick = "Quick"
    const val bench4Pinned = "4 pinned"
    const val bench4Unpinned = "4 unpinned"
    const val bench3Pinned = "3 pinned"
    const val bench8Threads = "8 threads"
    fun benchTg16k(kv: String) = "tg128 @ 16k $kv"

    // Small UI literals (SettingsSheet compute row, UnsupportedCpuScreen facts, BenchScreen results, ModelManager storage, FirstRun)
    const val cpuFallbackName = "CPU"
    fun cpuLine(soc: String, nBig: Int, nCores: Int, features: String, compute: String) = "CPU · $soc · $nBig big of $nCores cores · $features · $compute"
    const val soc = "SoC"
    const val cores = "Cores"
    fun coresLine(nCores: Int, nBig: Int) = "$nCores · $nBig big"
    const val yes = "yes"
    const val no = "no"
    const val results = "Results"
    const val pp = "pp"
    const val tg = "tg"
    const val pinnedCores = "pinned"
    const val freeCores = "free"
    fun storageLine(models: String, partial: String?, free: String, total: String) = "$models models${partial?.let { " ($it partial)" } ?: ""} · $free free of $total"
    const val textPlusVision = "text + vision"
    const val textModel = "text"
    fun downloadLine(size: String, vision: Boolean, licence: String) = "$size download · ${if (vision) textPlusVision else textModel} · $licence"
}
