package to.eyed.inferno.ui

// Every user-facing string lives here (hard-coded English, no strings.xml except app_name for
// the manifest). Grouped by screen; other packages add members, never rename.
object S {
    const val appName = "Inferno"

    // Generic actions
    const val ok = "OK"
    const val cancel = "Cancel"
    const val close = "Close"
    const val back = "Back"
    const val dismiss = "DISMISS"
    const val confirm = "Confirm"
    const val delete = "Delete"
    const val retry = "Retry"
    const val resume = "Resume"
    const val apply = "Apply"
    const val save = "Save"
    const val copy = "Copy"
    const val copied = "Copied"
    const val manage = "Manage"
    const val download = "Download"
    const val recommended = "Recommended"
    const val default = "Default"
    const val more = "More"
    const val tapAgainToConfirm = "Tap again to confirm. Irreversible."

    // Chat
    const val newChat = "New chat"
    const val openSidebar = "Open sidebar"
    const val closeSidebar = "Close sidebar"
    const val chooseModel = "Choose a model"
    const val chooseModelToStart = "Choose a model to start"
    const val chooseModelButton = "Choose model"
    const val emptyTitle = "Where should we begin?"
    const val emptySubtitle = "Runs entirely on this phone."
    const val composerPlaceholder = "Message Inferno…"
    const val composerLoadModelToStart = "Load a model to start"
    const val send = "Send"
    const val stop = "Stop"
    const val attach = "Attach"
    const val camera = "Camera"
    const val photos = "Photos"
    const val think = "Think"
    const val thinking = "Thinking…"
    const val thoughtFor = "Thought for"
    const val jumpToLatest = "Jump to latest"
    const val regenerate = "Regenerate"
    const val details = "Details"
    const val edit = "Edit"
    const val attachedImage = "Attached image"
    const val fullSizeImage = "Full-size image"
    const val removeImage = "Remove image"
    const val willSendWhenReady = "Will send when the model is ready"
    const val trimmingOlder = "Trimming older messages…"
    const val olderOutsideContext = "Older messages are outside the context window"
    const val contextAlmostFull = "Context is almost full"
    const val trimOlderMessages = "Trim older messages"
    const val answerComplete = "Answer complete"
    const val stopped = "stopped"
    const val interrupted = "interrupted"
    const val finishCurrentAnswer = "Finish the current answer first"
    const val couldNotReadImage = "Couldn't read that image"
    const val notEnoughMemoryForImage = "Not enough memory to read this image"
    const val messageExceedsContext = "This message alone exceeds the context window"
    const val phoneIsHot = "Phone is hot — running on fewer cores"
    const val noVision = "This model has no vision"
    const val noMemoryForVision = "Not enough memory for images with this model"
    const val turnDetails = "Turn details"
    const val copyAsJson = "Copy as JSON"

    // Sidebar
    const val search = "Search"
    const val searchChats = "Search chats"
    const val noChatsYet = "No chats yet"
    fun noChatsMatch(query: String) = "No chats match \"$query\""
    const val pinned = "Pinned"
    const val today = "Today"
    const val yesterday = "Yesterday"
    const val previous7Days = "Previous 7 days"
    const val older = "Older"
    const val archived = "Archived"
    const val rename = "Rename"
    const val pin = "Pin"
    const val unpin = "Unpin"
    const val archive = "Archive"
    const val unarchive = "Unarchive"
    const val models = "Models"
    const val noModelLoaded = "No model loaded"
    const val benchmark = "Benchmark"
    const val settings = "Settings"

    // Engine states
    const val loading = "Loading…"
    const val calibrating = "Calibrating…"
    const val readingWeights = "Reading weights"
    const val creatingContext = "Creating context"
    const val loadingVision = "Loading vision"
    const val failed = "Failed"
    const val suspended = "Suspended"
    fun loadingModel(name: String) = "Loading $name…"

    // Models
    const val model = "Model"
    const val getModels = "Get models"
    const val nothingDownloadedYet = "Nothing downloaded yet"
    const val curatedForThisPhone = "Curated for this phone"
    const val contextLength = "Context length"
    const val generation = "Generation"
    const val importGguf = "Import GGUF"
    const val discardDownload = "Discard download"
    const val paused = "paused"
    const val noConnection = "no connection"
    const val pausedBySystem = "paused by the system"
    const val waitForWifi = "Wait for Wi-Fi"
    const val downloadAnyway = "Download anyway"
    const val alwaysAllow = "Always allow"
    const val offlineNotice = "You're offline. Downloaded models still work."
    const val notificationsNotice = "Enable notifications to see download progress in the shade"
    const val q4Footer = "Q4_0 files run fastest on this phone (KleidiAI dotprod kernels). Q8_0 mmproj recommended."
    const val autoMax = "Auto (max)"
    const val contextNote = "Auto picks the largest context that fits in memory. Q8_0 halves KV memory and requires flash attention."

    // Settings
    const val inference = "Inference"
    const val chat = "Chat"
    const val storage = "Storage"
    const val advanced = "Advanced"
    const val about = "About"
    const val dangerZone = "Danger zone"
    const val systemPrompt = "System prompt"
    const val streamingAnimations = "Streaming animations"
    const val haptics = "Haptics"
    const val appliedAfterReload = "Applied after reload"
    const val openSourceLicences = "Open-source licences"
    const val sourceCode = "Source code"
    const val privacy = "Privacy"
    const val privacyLine = "Nothing leaves this phone."
    const val deleteAllChats = "Delete all chats"
    const val deleteAllModels = "Delete all models"
    const val chatsStoredLocally = "Chats are stored only on this device."

    // Onboarding
    const val firstRunTagline = "Private AI that runs on your phone. Nothing leaves the device."
    const val downloadAndStart = "Download and start"
    const val chooseDifferentModel = "Choose a different model"
    const val importAGguf = "Import a GGUF"
    const val unsupportedCpu = "This phone's CPU lacks the dotprod/fp16 instructions Inferno needs."

    // Bench
    const val loadModelFirst = "Load a model first"
    const val runQuick = "Run quick (pp512 / tg128)"
    const val runThreadMatrix = "Run thread matrix"
    const val runBenchmarkHint = "Run a benchmark to see numbers for this phone"
    const val shareJson = "Share JSON"

    // Accessibility labels for decorative / structural elements
    const val dragHandle = "Drag handle"
    const val selected = "Selected"

    // Create image / Gallery (WP9b-ui)
    const val create = "Create"
    const val createImage = "Create image"
    const val gallery = "Gallery"
    const val describeImage = "Describe the image…"
    const val generate = "Generate"
    const val imageModel = "Model"
    const val options = "Options"
    const val size = "Size"
    const val steps = "Steps"
    const val seed = "Seed"
    const val randomSeed = "Random"
    const val randomSeedHint = "New every time"
    const val useRandomSeed = "Use a random seed"
    const val reuseLastSeed = "Reuse last seed"
    const val copySeed = "Copy seed"
    const val fewerSteps = "Fewer steps"
    const val moreSteps = "More steps"
    const val saveToPhotos = "Save"
    const val savedToPhotos = "Saved to Photos"
    const val share = "Share"
    const val useAsAttachment = "Attach"
    const val again = "Again"
    const val downloaded = "Downloaded"
    const val verifying = "Verifying…"
    const val waiting = "Waiting…"
    const val discard = "Discard"
    const val downloading = "Downloading"
    const val resumeDownload = "Resume download"
    const val retryDownload = "Retry download"
    const val noImagesYet = "No images yet"
    const val noImagesHint = "Images you create will appear here."
    const val generatedImage = "Generated image"
    const val latentPreview = "Preview"
    const val deleteImage = "Delete image"
    const val openImage = "Open image"
    const val starting = "Starting"
    const val finishing = "Finishing"
    const val describeFirst = "Describe the image first"
    fun loadingImageModel(name: String) = "Loading $name…"
    fun stepOf(step: Int, total: Int) = "Step $step/$total"
    fun downloadModel(name: String, size: String) = "Download $name · $size"
    fun square(px: Int) = "$px × $px"

    /** "~12 s" / "~1 min" / "~1 min 8 s": whole seconds, minutes once past 60. */
    fun eta(seconds: Int): String {
        val s = seconds.coerceAtLeast(0)
        if (s < 60) return "~$s s"
        val m = s / 60
        val r = s % 60
        return if (r == 0) "~$m min" else "~$m min $r s"
    }

    /** "8.1 s" / "1 min 8 s" (6.2): one decimal under a minute, whole seconds above. */
    fun duration(ms: Long): String {
        val s = ms / 1000.0
        if (s < 60) return String.format(java.util.Locale.US, "%.1f s", s)
        val m = (s / 60).toInt()
        val r = (s - m * 60).toInt()
        return if (r == 0) "$m min" else "$m min $r s"
    }
}
